---
title: "HW_3"
author: "Suyi TU"
date: "2017/8/6"
output: md_document
---

```{r setup,echo=FALSE,include=FALSE}
library(proxy)
```


```{r}
social_market <- read.csv('~/Documents/SourceTree/STA380/data/social_marketing.csv')
#Discard users whose most frequent tweets are adult/spam
discard<-which(apply(social_market[,-1],1,function(x) x['spam']==max(x) || x['adult']==max(x)))
social_market<-social_market[-discard,]
```

```{r}
#TF
sum_raw<-apply(social_market[,-1],1,sum)
TF<-social_market[,2:ncol(social_market)]/sum_raw
sum_tf<-sort(apply(TF,2,mean),decreasing=TRUE)
barplot(sum_tf[1:10],main='Term frequency')
print(names(sum_tf[1:10]))
```
```{r}
#TFIDF
EXI_NUM<-apply(social_market[,-1]>0,2,function(x){table(x)['TRUE']})
IDF<-as.numeric(log(nrow(social_market)/EXI_NUM))
TFIDF = data.frame(t(t(TF)*IDF))
mean_tfidf<-sort(apply(TFIDF,2,mean),decreasing=TRUE)
barplot(mean_tfidf[1:10],main='TFIDF')
print(names(mean_tfidf[1:10]))
```
```{r}
#hclust
d.cosine<-dist(TFIDF,method='cosine')
hc.ratio.cosine<-hclust(d.cosine,method='ward.D2')
```

```{r}
##This outputs detailed clusters from 2-5
#will be taken out for the final submission
for(i in 2:5){
  out.cluster = cutree(hc.ratio.cosine,k=i)
  TFIDF['cluster'] = out.cluster
  for(j in 1:i){
    cate = apply(TFIDF[TFIDF['cluster']==j,-1],2,sum)
    cate.sort = sort(cate[-length(cate)],decreasing=TRUE)
    print(names(cate.sort)[1:10])
    cat('\n')
  }
  cat('\n')
}
```

```{r}
#hclust
#choose cluster 2
out.cluster = cutree(hc.ratio.cosine,k=2)
TFIDF['cluster'] = out.cluster
for(j in 1:2){
    cate = apply(TFIDF[TFIDF['cluster']==j,-1],2,mean)
    cate.sort = sort(cate[-length(cate)],decreasing=TRUE)
    barplot(cate.sort[1:10])
    print(names(cate.sort)[1:10])
  }
```

#### From the topics of high TFIDF-socres in both clusters, we can infer that first cluster represents working people (most likely single), and the second represents school boys/girls.